# Notifies orchestrator (source repo workflows) that GitOps PR has been merged
# So that the orchestrator can proceed with the next step in the pipeline

name: notify-on-pr

on:
  push:
    branches:
      - '*'
      - '!main'
    paths-ignore:
      - '.github/**'      

jobs:
  notify-on-pr:
    runs-on: ubuntu-latest    
    permissions: write-all        
    steps: 
    - name: Checkout Gitops
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.commit.sha }}

    - name: Get Tracking Info 
      run: |
          .github/workflows/utils/get-tracking-info.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_ID: ${{ github.sha }}

    - name: Notify Orchestrator
      run: |
          gh workflow run post-deployment.yml -f environment="$GITHUB_REF_NAME" -f promoted_commit_id="$PROMOTED_COMMIT_ID" -f commit_id="$GITHUB_SHA" -f promotion="$PROMOTION" -f image_tag="$IMAGE_TAG" -f version="$VERSION" -r main -R "$SRC_REPO"       
      env:
        GH_TOKEN: ${{ secrets.CD_BOOTSTRAP_TOKEN }}
        SRC_REPO: ${{ vars.SRC_REPO }}
